Antidote-for-Tox/Antidote

Antidote/ChatViewController.m

Small PR for enable/disabling call button based on the status of friend.

Enable/Disable call button based on friend's online status

---

Antidote.xcodeproj/project.pbxproj
Antidote/AbstractCallViewController.m
Antidote/CallNavigationViewController.h
Antidote/CallNavigationViewController.m
Antidote/ChatViewController.m
Antidote/ToxListener.m

Moved the navigation controller to it's own class, along with the
blurred logic.
Might be a little too dark? I could make the alpha `0.9` as below:

Improve blurred background

---

Antidote/CallsManager.m

Add logging to CallsManager

---

Antidote/ChatViewController.m

Not audio related but saw this while reading JSQMessageCollection Documentation :smile:

Add chat time stamps for every 3

---

Antidote/AllChatsViewController.m

This now shows the time stamp on the `AllChatsViewController` like so:

Call activity shown on allchatsviewcontroller

---

Antidote/ActiveCallViewController.h
Antidote/ActiveCallViewController.m
Antidote/CallsManager.m
Antidote/PauseCallTableViewCell.h
Antidote/PauseCallTableViewCell.m
Podfile

Responsible for reloading the tableViewOfPausedCalls.

Add NSTimer for refreshing pause calls when tableview is shown

---

Antidote/AbstractCallViewController.m
Antidote/ActiveCallViewController.m
Antidote/AppearanceManager.h
Antidote/AppearanceManager.m
Antidote/PauseCallTableViewCell.m

Some UI improvements

---

Antidote/AbstractCallViewController.m
Antidote/ActiveCallViewController.m
Antidote/DialingCallViewController.m
Antidote/RingingCallViewController.m

For https://github.com/Antidote-for-Tox/Antidote/issues/82

Clean up MASConstraints

---

Antidote/ActiveCallViewController.m
Antidote/CallsManager.m

Screen will turn off when phone is placed up to the ear while in
a call.

Feature: Add Proximity sensor while in call

---

Antidote/ActiveCallViewController.h
Antidote/ActiveCallViewController.m
Antidote/CallsManager.m

This is for https://github.com/Antidote-for-Tox/Antidote/issues/86
Rather than creating a whole new view controller, I thought it would make more sense to use ActiveCallViewController since the call is considered `OCTCallActive`. I didn't add the "please wait..." label above the end call button. Do you think it's necessary? If so I need to figure out a way to juggle displaying the incoming call and please wait at the same time.
Here is a screen shot:

Feature: Pause View Screen #86

---

Antidote/CallsManager.m
Antidote/ErrorHandler.h
Antidote/ErrorHandler.m

For https://github.com/Antidote-for-Tox/Antidote/issues/95

Add logging for calls manager

---

Antidote/RingTonePlayer.m

Default ringtones to speaker and add logging

---

Antidote/AbstractCallViewController.m
Antidote/ActiveCallViewController.m
Antidote/VideoAndPreviewView.h
Antidote/VideoAndPreviewView.m

Video screen is always full screen now. If you prefer to have it expand on tap instead, let me know and I can change it :smile: 
Related: https://github.com/Antidote-for-Tox/Antidote/issues/104

Autolayout updates

---

Antidote/ActiveCallViewController.m

Resolves https://github.com/Antidote-for-Tox/Antidote/issues/111
Though I might want to move video view controller to a separate view controller to since `ActiveCallViewController` is getting a little bit.

Set opaque to YES when video is shown

---

Antidote/CompactControlsView.m

Better look for the buttons. Though maybe I shouldn't change the alpha for the end call.
(http://i.snag.gy/IWkDN.jpg)

Change button styles for compactViewControls

---

Antidote/AbstractCallViewController.m
Antidote/ActiveCallViewController.m

Remove opaque from call view controllers. These aren't needed at all.

Remove opaque from call view controllers

---

Antidote/CallsManager.h
Antidote/CallsManager.m
Antidote/ChatViewController.m
Antidote/FriendCardViewController.m

https://github.com/Antidote-for-Tox/Antidote/issues/118

Add call buttons to friend card controller

---

Antidote/CallsManager.m

https://github.com/Antidote-for-Tox/Antidote/issues/119

Disable screen fade when call manager is alive

---

Antidote.xcodeproj/project.pbxproj
Antidote/ActiveCallViewController.h
Antidote/ActiveCallViewController.m
Antidote/AudioCallViewController.h
Antidote/AudioCallViewController.m
Antidote/CallsManager.m
Antidote/CompactControlsView.m
Antidote/ExpandedControlsView.h
Antidote/ExpandedControlsView.m
Antidote/VideoCallViewController.h
Antidote/VideoCallViewController.m

Both audio and video controllers are a subclass of `ActiveCallViewController`.

Separate Audio and Video into two controllers

---

Antidote/AudioCallViewController.m

For issue https://github.com/Antidote-for-Tox/Antidote/issues/116

Avatar shown during audio call (Landscape)

---

Antidote/AbstractCallViewController.m
Antidote/VideoAndPreviewView.m

https://github.com/Antidote-for-Tox/Antidote/issues/126
https://github.com/Antidote-for-Tox/Antidote/issues/128

Fix for #126 and #128

---

Antidote/AbstractCallViewController.m

https://github.com/Antidote-for-Tox/Antidote/issues/134

Fix name but off when landscape

---

Antidote/DialingCallViewController.m

For https://github.com/Antidote-for-Tox/Antidote/issues/110
Tested on all screen sizes and it looks good landscape/portrait :+1:

Fix autolayout for dialing call view control

---

Antidote/RingingCallViewController.m

https://github.com/Antidote-for-Tox/Antidote/issues/110
Tested on all devices :+1:

Fix avatar sizing for Ringing View Controller
